@extends('admin.layout.master')
@section('title','Push Notifications')
@section('page-header')
    <i class="material-icons">notifications</i> Notifications
@stop
@section('content')
    <div class="row">
        <div class="col-6 card card-body">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <tr>
                            <th>SL</th>
                            <th >Notification</th>
                            <th >Generated By</th>
                            <th >Action</th>
                        </tr>
                    </tr>
                </thead>
                <tbody>
                    @forelse($notifications as $item)
                        <tr>
                            <td>{{ ($notifications->total()-$loop->index)-(($notifications->currentpage()-1) * $notifications->perpage() ) }}</td>
                            <td>
                                <div class="row">
                                    <div class="col-9">
                                        <h5>{{ $item->title }}</h5>
                                        <small class="text-muted">{!! $item->body !!}</small>
                                    </div>
                                    @if($item->image != NULL)
                                        <div class="col-3">
                                            <img src="{{ asset($item->image) }}" alt="Image" class="img img-thumbnail" width="100px" height="100px">
                                        </div>
                                    @endif
                                </div>
                                <div class="row">
                                    <small class="col text-muted text-center">
                                        {{$item->created_at->format('d M Y h:i A')}}
                                    </small>
                                </div>
                            </td>
                            <td>{{ $item->admin->name ?? $item->admin->email }}</td>
                            <td></td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5">NO NOTIFICATIONS YET</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        <div class="col-6">
            <div class="card rounded shadow">
                <div class="card-body">
                    <form action="{{ route('admin.notification.send') }}" enctype="multipart/form-data" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="">Title</label>
                            <input type="text" name="title" class="form-control" value="{{ old('title') }}">
                        </div>
                        <div class="form-group">
                            <label for="">Body</label>
                            <textarea class="form-control" name="body" cols="30" rows="5">{{ old('body') }}</textarea>
                        </div>
                        <div class="custom-file">
                            <input type="file" name="image" class="custom-file-input" id="customFile">
                            <label class="custom-file-label" for="customFile">Choose Image</label>
                          </div>
                        <hr>
                        <button class="btn btn-sm btn-success" type="submit"><i class="material-icons">notifications</i>&nbsp;Broadcast</button>
                    </form>
                </div>
            </div>
        </div>
        
    </div>
    
@endsection

@push('js')
    <script type="text/javascript">
        $(".custom-file-input").on("change", function() {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
          });
        
    </script>
@endpush
